<?php

namespace Database\Seeders;

use App\Models\MerchandiseCode;
use Illuminate\Database\Seeder;

class MerchandiseCodeSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        MerchandiseCode::insert([
            ['code' => "RV01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "V-Black NBR 7Mpa rubber Gasket"],
            ['code' => "RV02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "V-Black EPDM 8Mpa rubber Gasket"],
            ['code' => "RV03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "V-Black CR 6Mpa rubber Gasket"],
            ['code' => "RV04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "V-Black NBR 7Mpa Rubber with ply Gasket"],
            ['code' => "RC01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Black NBR 5Mpa rubber Gasket"],
            ['code' => "RC02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Black NBR 8Mpa Rubber Gasket"],
            ['code' => "RC03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Black EPDM 5Mpa rubber Gasket"],
            ['code' => "RC04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Black EPDM 8Mpa rubber Gasket"],
            ['code' => "RC05", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Black CR 4Mpa rubber Gasket"],
            ['code' => "RC06", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Black CR 6Mpa rubber Gasket"],
            ['code' => "RC07", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Black SBR 3Mpa Rubber Gasket"],
            ['code' => "RC08", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-White EPDM rubber Gasket"],
            ['code' => "RT01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Tiger- Black NBR Rubber Gasket"],
            ['code' => "RA01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "P559 - NBR Rubber Gasket"],
            ['code' => "RA02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "P9540- NBR/SBR Rubber Gasket"],
            ['code' => "RA03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "N572 - CR Rubber Gasket"],
            ['code' => "RA04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "N9581 - CR/SBR Rubber Gasket"],
            ['code' => "RA05", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "E9566 - EPDM Rubber Gasket"],
            ['code' => "RA06", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "E628 - EPDM Rubber Gasket"],
            ['code' => "RA07", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "FDA Hell EPDM Rubber Gasket"],
            ['code' => "RA08", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "FKM(Viton) Rubber Gasket"],
            ['code' => "RC13", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Grey Ribbed Rubber "],
            ['code' => "RC14", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Blue Ribbed Rubber "],
            ['code' => "RC15", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Green Ribbed Rubber "],
            ['code' => "RC16", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Red Ribbed Rubber "],
            ['code' => "RC17", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Grey Round botton Rubber "],
            ['code' => "RC18", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Blue  Round botton Rubber "],
            ['code' => "RC19", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Green Round botton Rubber "],
            ['code' => "RC20", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Red  Round botton Rubber "],
            ['code' => "RJ01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JE10-Black EPDM Rubber Gasket"],
            ['code' => "RJ03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JE20-Black EPDM Rubber Gasket"],
            ['code' => "RJ05", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JE30-Black EPDM Rubber Gasket"],
            ['code' => "RJ09", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JEWF-White EPDM FDA Rubber Gasket"],
            ['code' => "RJ06", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JN10-Black NBR Rubber Gasket"],
            ['code' => "RJ07", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JN30-Black NBR Rubber Gasket"],
            ['code' => "RJ04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JNDM-Black NBR Rubber Gasket"],
            ['code' => "RJ08", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JC30-Black CR (neoprene) Rubber Gasket"],
            ['code' => "RJ02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JFKM-Black FKM (Viton) Rubber Gasket"],
            ['code' => "RZ01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "ZE10-Black EPDM Rubber Gasket"],
            ['code' => "RZ02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "ZE30-Black EPDM Rubber Gasket"],
            ['code' => "RZ03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "ZE100-Black EPDM Rubber Gasket"],
            ['code' => "RZ04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "ZN10-Black NBR Rubber Gasket"],
            ['code' => "RZ05", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "ZN30-Black NBR Rubber Gasket"],
            ['code' => "RZ06", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "ZN100-Black NBR Rubber Gasket"],
            ['code' => "RZ07", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "ZEWF-White EPDM FDA Rubber Gasket"],
            ['code' => "RZ08", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "ZFKM-Black FKM (Viton) Rubber Gasket"],
            ['code' => "RT03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Trelleborg B609- Black NBR Rubber Gasket"],
            ['code' => "RZ09", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "ZNS Black NR/SBR Rubber Gasket"],
            ['code' => "RN01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JS Black NR/SBR Rubber Gasket"],
            ['code' => "RB01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JSV Black NR/SBR Rubber Gasket"],
            ['code' => "RC09", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Translucent silicone Gasket"],
            ['code' => "RC10", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-Red Silicone Gasket"],
            ['code' => "RC11", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-White Silicone Gasket"],
            ['code' => "RC12", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "C-White Foam silicone Gasket"],
            ['code' => "RE01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "E-Transparent silicone Gasket"],
            ['code' => "RE02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "E-Red silicone Gasket"],
            ['code' => "RE03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "E-White Foam silicone Gasket"],
            ['code' => "CC01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Ceramic fiber cloth with steel wire reinforced Gasket"],
            ['code' => "CC02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Ceramic fiber cloth with glass fiber reinforced Gasket"],
            ['code' => "BG01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "BG400- Non asbestos Gasket"],
            ['code' => "BG02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "BG1005 - Non asbestos Gasket"],
            ['code' => "BG03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "BG1500 - Non asbestos Gasket"],
            ['code' => "BG04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "BG1560- Non Asbestos Gasket"],
            ['code' => "BG05", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "BG2000 - Non asbestos Gasket"],
            ['code' => "BG06", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "BG2000R- Non Asbestos Gasket"],
            ['code' => "BG07", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "BG3010 - Non asbestos Gasket"],
            ['code' => "LM01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "L430- Non asbestos Gasket"],
            ['code' => "LM02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "L441- Non asbestos Gasket"],
            ['code' => "LM03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "L443- Non asbestos Gasket"],
            ['code' => "LM04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "L450 Fire Safe- Non asbestos Gasket"],
            ['code' => "TB01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Tombo 1995- Non asbestos Gasket"],
            ['code' => "TB02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Tombo 1935- Non asbestos Gasket"],
            ['code' => "TD01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Teadit NA1005 - Non asbestos Gasket"],
            ['code' => "TD02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Teadit NA1122 - Non asbestos Gasket"],
            ['code' => "TD03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Teadit NA1100 - Non asbestos Gasket"],
            ['code' => "KL01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Klingersil C4400- Non asbestos Gasket"],
            ['code' => "KL05", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Klingersil C4430- Non asbestos Gasket"],
            ['code' => "KL04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Milam PSS200 - Klinger Mica Laminate Gasket"],
            ['code' => "VQ01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "VS6600- Non Asbestos  Gasket"],
            ['code' => "VQ02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "VS6602- Non Asbestos  Gasket"],
            ['code' => "VQ03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "VS6500- Non Asbestos  Gasket"],
            ['code' => "VQ04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "VS6500AC- Non Asbestos  Gasket"],
            ['code' => "VQ05", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "VS6502- Non Asbestos  Gasket"],
            ['code' => "AF01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "AFM100- Black Non Asbestos Gasket"],
            ['code' => "AF02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "AFM100- Green Non Asbestos Gasket"],
            ['code' => "BP01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "BELPACSA 320- Non Asbestos Gasket"],
            ['code' => "BP02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Belpha-Graphite tanged SS304  Gasket"],
            ['code' => "BP03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Belphacompac Graphite Gasket"],
            ['code' => "NV01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Novatech special gasket"],
            ['code' => "NV02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Novatec Premium Gasket"],
            ['code' => "GA01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Garlock 9900 Gasket"],
            ['code' => "DO01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Donit Tesnit BA-U Gasket"],
            ['code' => "DO02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Donit Tesnit BA-203 Gasket"],
            ['code' => "DO03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Donit Tesnit BA-GL Gasket"],
            ['code' => "DO06", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Donit Tesnit BA-50 Gasket"],
            ['code' => "DO07", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Donit Tesnit BA-F Gasket"],
            ['code' => "WJ01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JXB 450- Asbestos Gasket"],
            ['code' => "KL02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Klingerit universal 3XA- Asbestos Gasket"],
            ['code' => "KL03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Klingerit Oilit 3XA- Asbestos Gasket"],
            ['code' => "CJ01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "CJ9- Asbestos Gasket"],
            ['code' => "HX01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "HUXU200-Asbestos Gasket"],
            ['code' => "HX02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "HUXU450-Asbestos Gasket"],
            ['code' => "CA01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "CAZ432 Ro- Asbestos Gasket"],
            ['code' => "CA02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "CAZ432 Rom - Asbestos Gasket"],
            ['code' => "CA03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "CAZ 470 Cork rubber sheet, hardness 55-70 Gasket"],
            ['code' => "CA04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "CAZ 480 Golden Mica sheet Gasket"],
            ['code' => "CA05", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "CAZ 480T Golden Mica Sheet Gasket"],
            ['code' => "CA06", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "CAZ 482H Hard Mica Sheet Gasket"],
            ['code' => "CA07", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "420TG-Compressed with graphite Gasket"],
            ['code' => "AB01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Blue Asbestos Gasket"],
            ['code' => "KL06", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Milam PSS300 - Klinger Mica Laminate Gasket"],
            ['code' => "SL01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF GP 150 Gasket"],
            ['code' => "SL02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF GP 200 Steel Gasket"],
            ['code' => "SL03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF 347 Gasket"],
            ['code' => "SL04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF OIL 220 Gasket"],
            ['code' => "SL05", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF OIL 250 Gasket"],
            ['code' => "SL06", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF OIL 250 Steel Gasket"],
            ['code' => "SL07", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF Acid 200 Gasket"],
            ['code' => "SL08", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF 482 Gasket"],
            ['code' => "SL09", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF GF 300 Gasket"],
            ['code' => "SL10", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF C350 Gasket"],
            ['code' => "SL11", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF 572 Gasket"],
            ['code' => "SL12", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Superlite AF Oil Steel 350 Gasket"],
            ['code' => "DO05", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "MICALIT F Gasket"],
            ['code' => "JE01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "LEAKBLOK Premium 100- Non asbestos Gasket"],
            ['code' => "JE02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "LEAKBLOK Premium 200- Non asbestos Gasket"],
            ['code' => "GC01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Graphite with tanged  SS304 Inserted Gasket"],
            ['code' => "GC02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Graphite with tanged  SS316 Inserted Gasket"],
            ['code' => "GC03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Graphite with flat SS304 Inserted Gasket"],
            ['code' => "GC04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Graphite with flat SS316 Inserted Gasket"],
            ['code' => "GC05", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Graphite with wire mesh SS304 Inserted Gasket"],
            ['code' => "GC06", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Graphite with wire mesh SS316 Inserted Gasket"],
            ['code' => "GC07", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Flexible Graphite Gasket"],
            ['code' => "GD01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "GRAFILIT SL-Graphite with SS316 foil inserted Gasket"],
            ['code' => "GD02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "GRAFILIT SP-Graphite with tanged SS316 inserted Gasket"],
            ['code' => "GJ01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JIC4201-B Starfoil-Graphite with tanged SS inserted Gasket"],
            ['code' => "PC01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Pure PTFE Gasket"],
            ['code' => "PC02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Glass PTFE Gasket"],
            ['code' => "PC03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Expanded PTFE Gasket"],
            ['code' => "PG01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Gylon 3500 Gasket"],
            ['code' => "PG02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Gylon 3510 Gasket"],
            ['code' => "PG03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Gylon 3504 Gasket"],
            ['code' => "PG04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Gylon STD 3501E Gasket"],
            ['code' => "PK01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Klinger Topchem 2000 Gasket"],
            ['code' => "PD01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Doniflon 2010 Gasket"],
            ['code' => "PD02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Doniflon 2020 Gasket"],
            ['code' => "PD03", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Doniflon 2030 Gasket"],
            ['code' => "PD04", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "Doniflon 900E Gasket"],
            ['code' => "PJ01", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "JIC8305G Starflon- Reinforced PTFE Gasket"],
            ['code' => "PJ02", 'prefix_code' => null, 'infix_code' => 'SG', 'summary' => "PTFE virgin - 8305"],
            //
            ['code' => "A01", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "150#-RF-B16.5"],
            ['code' => "A02", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "150#-FF-B16.5"],
            ['code' => "A17", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "300/400/600#-RF-B16.5"],
            ['code' => "A03", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "300#-RF-B16.5"],
            ['code' => "A04", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "300#-FF-B16.5"],
            ['code' => "A13", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "25#-FF-B16.1"],
            ['code' => "A15", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "125#-FF-B16.1"],
            ['code' => "A12", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "25#-RF-B16.1"],
            ['code' => "A14", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "125#-RF-B16.1"],
            ['code' => "A16", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "250#-RF-B16.1"],
            ['code' => "A05", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "150#-RF-B16.47 A"],
            ['code' => "A07", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "300#-RF-B16.47 A"],
            ['code' => "A09", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "75#-RF-B16.47 B"],
            ['code' => "A06", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "150#-RF-B16.47 B"],
            ['code' => "A08", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "300#-RF-B16.47 B"],
            ['code' => "A10", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "175#-RF-B16.47 B"],
            ['code' => "A11", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "350#-RF-B16.47 B"],
            ['code' => "A18", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "400#-RF-B16.5"],
            ['code' => "A19", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "600#-RF-B16.5"],
            ['code' => "A20", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "900#-RF-B16.5"],
            ['code' => "A22", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "400#-RF-B16.47 A"],
            ['code' => "A23", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "600#-RF-B16.47 A"],
            ['code' => "A24", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "400#-RF-B16.47 B"],
            ['code' => "A25", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "600#-RF-B16.47 B"],
            ['code' => "A21", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "150#-FF-B16.24"],
            ['code' => "A26", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "300#-FF-B16.24"],
            ['code' => "A27", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "150#-FF-MSS SP-51"],
            ['code' => "J03", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "5K-RF"],
            ['code' => "J04", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "5K-FF"],
            ['code' => "J16", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "10/16/20K-RF"],
            ['code' => "J05", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "10K-RF"],
            ['code' => "J19", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "10/16/20K-FF"],
            ['code' => "J06", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "10K-FF"],
            ['code' => "J17", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "16/20K-RF"],
            ['code' => "J07", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "16K-RF"],
            ['code' => "J08", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "16/20K-FF"],
            ['code' => "J09", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "20K-RF"],
            ['code' => "J12", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "40K-RF"],
            ['code' => "J18", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "30/40K-RF"],
            ['code' => "J11", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "30K-RF"],
            ['code' => "J01", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "2K-RF"],
            ['code' => "J13", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "63K-RF"],
            ['code' => "J02", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "2K-FF"],
            ['code' => "J14", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "M&F JIS"],
            ['code' => "J15", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "T&G JIS"],
            ['code' => "P02", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN6-RF"],
            ['code' => "P03", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN6-FF"],
            ['code' => "P04", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN10-RF"],
            ['code' => "P05", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN10-FF"],
            ['code' => "P06", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN16-RF"],
            ['code' => "P07", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN16-FF"],
            ['code' => "P08", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN25-RF"],
            ['code' => "P09", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN25-FF"],
            ['code' => "P10", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN40-RF"],
            ['code' => "P11", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN40-FF"],
            ['code' => "P01", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN2.5-RF"],
            ['code' => "E01", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN2.5/6-RF"],
            ['code' => "E02", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN2.5/6-FF"],
            ['code' => "E03", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN2.5-RF"],
            ['code' => "E04", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN6-RF"],
            ['code' => "E05", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN10/16/25/40-RF"],
            ['code' => "E06", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN10/16-RF"],
            ['code' => "E07", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN10-RF"],
            ['code' => "E08", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN10/16/25/40-FF"],
            ['code' => "E09", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN10/16-FF"],
            ['code' => "E10", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN10-FF"],
            ['code' => "E11", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN16-RF"],
            ['code' => "E12", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN16-FF"],
            ['code' => "E13", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN25/40-RF"],
            ['code' => "E14", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN25-RF"],
            ['code' => "E15", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN25/40-FF"],
            ['code' => "E16", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN25-FF"],
            ['code' => "E17", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN40-RF"],
            ['code' => "E18", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN40-FF"],
            ['code' => "E19", 'prefix_code' => "SG", 'infix_code' => "STD", 'summary' => "PN63-RF"],
            ['code' => "CIR", 'prefix_code' => "SG", 'infix_code' => "NSTD", 'summary' => ""],
            ['code' => "CIF", 'prefix_code' => "SG", 'infix_code' => "NSTD", 'summary' => ""],
            ['code' => "RER", 'prefix_code' => "SG", 'infix_code' => "NSTD", 'summary' => ""],
            ['code' => "REF", 'prefix_code' => "SG", 'infix_code' => "NSTD", 'summary' => ""],
            ['code' => "OVR", 'prefix_code' => "SG", 'infix_code' => "NSTD", 'summary' => ""],
            ['code' => "OBF", 'prefix_code' => "SG", 'infix_code' => "NSTD", 'summary' => ""],
            //
            ['code' => "S1" , 'prefix_code' => null, 'infix_code' => "SWG", 'summary' => ""],
            ['code' => "S2" , 'prefix_code' => null, 'infix_code' => "SWG", 'summary' => ""],
            ['code' => "S3" , 'prefix_code' => null, 'infix_code' => "SWG", 'summary' => ""],
            ['code' => "S4" , 'prefix_code' => null, 'infix_code' => "SWG", 'summary' => ""],
            //
            ['code' => "A01", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "150# (B)"],
            ['code' => "A02", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "300# (B)"],
            ['code' => "A03", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "300/400/600# (B)"],
            ['code' => "A04", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "400# (B)"],
            ['code' => "A05", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "600# (B)"],
            ['code' => "A06", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "900# (B)"],
            ['code' => "A07", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "900/1500# (B)"],
            ['code' => "A08", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "1500# (B)"],
            ['code' => "A09", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "2500# (B)"],
            ['code' => "A10", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "150# (A)"],
            ['code' => "A11", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "300# (A)"],
            ['code' => "A12", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "400# (A)"],
            ['code' => "A13", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "600# (A)"],
            ['code' => "A14", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "900# (A)"],
            ['code' => "A15", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "150# (LA)/175# (TA)"],
            ['code' => "A16", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "300# (LA)/350# (TA)"],
            ['code' => "A17", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "125# (TA)"],
            ['code' => "A18", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "250# (TA)"],
            ['code' => "A19", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI T&G-S"],
            ['code' => "A20", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI T&G-L"],
            ['code' => "A21", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI M&FM 150/300#-S"],
            ['code' => "A22", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI M&FM 400/600#-S"],
            ['code' => "A23", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI M&FM 900#-S"],
            ['code' => "A24", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI M&FM 1500#-S"],
            ['code' => "A25", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI M&FM 2500#-S"],
            ['code' => "A26", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI M&FM 150/300#-L"],
            ['code' => "A27", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI M&FM 400/600#-L"],
            ['code' => "A28", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI M&FM 900#-L"],
            ['code' => "A29", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI M&FM 1500#-L"],
            ['code' => "A30", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "ANSI M&FM 2500#-L"],
            ['code' => "J01", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "5K"],
            ['code' => "J02", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "10,16,20K"],
            ['code' => "J03", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "10K"],
            ['code' => "J04", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "16,20K"],
            ['code' => "J05", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "30K"],
            ['code' => "J06", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "40K"],
            ['code' => "J07", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "63K"],
            ['code' => "J08", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "10K (L)"],
            ['code' => "J09", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "16K (L)"],
            ['code' => "J10", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "20K (L)"],
            ['code' => "J11", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "Jis T&G"],
            ['code' => "J12", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "Jis M&FM"],
            ['code' => "P01", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN10,16,25,40"],
            ['code' => "P02", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN10,16"],
            ['code' => "P03", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN10"],
            ['code' => "P04", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN16"],
            ['code' => "P05", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN25,40"],
            ['code' => "P06", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN25"],
            ['code' => "P07", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN40"],
            ['code' => "P08", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN64,100,160"],
            ['code' => "P09", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN64"],
            ['code' => "P10", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN100,160"],
            ['code' => "P11", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN100"],
            ['code' => "P12", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN160"],
            ['code' => "P13", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN250"],
            ['code' => "E01", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN10,25,40"],
            ['code' => "E02", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN10"],
            ['code' => "E03", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN25,40"],
            ['code' => "E04", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN25"],
            ['code' => "E05", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN40"],
            ['code' => "E06", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN63,100,160"],
            ['code' => "E07", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN63"],
            ['code' => "E08", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN100,160"],
            ['code' => "E09", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN100"],
            ['code' => "E10", 'prefix_code' => "SWG", 'infix_code' => "STD", 'summary' => "PN160"],
            ['code' => "CI", 'prefix_code' => "SWG", 'infix_code' => "NSTD", 'summary' => ""],
            ['code' => "EL", 'prefix_code' => "SWG", 'infix_code' => "NSTD", 'summary' => ""],

            ['code' => "RTOC", 'prefix_code' => null, 'infix_code' => "RTJ", 'summary' => ""],
            ['code' => "RTOV", 'prefix_code' => null, 'infix_code' => "RTJ", 'summary' => ""],
            ['code' => "ROOC", 'prefix_code' => null, 'infix_code' => "RTJ", 'summary' => ""],
            ['code' => "ROOV", 'prefix_code' => null, 'infix_code' => "RTJ", 'summary' => ""],

            ['code' => "PAC01", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Expanded graphite packing "],
            ['code' => "PAC02", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Graphite Packing reinfored with Nickel (Inconel) wire"],
            ['code' => "PAC03", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Cotton packing with Graphite & oil"],
            ['code' => "PAC04", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Cotton packing with grease (Yellow)"],
            ['code' => "PAC05", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Ramie packing with silicone rubber core"],
            ['code' => "PAC06", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Aramid fiber packing impregnated with PTFE"],
            ['code' => "PAC07", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "White PTFE packing with Aramid corners"],
            ['code' => "PAC08", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Graphite packing with carbon fiber corners"],
            ['code' => "PAC09", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Graphited PTFE packing with aramid corners"],
            ['code' => "PAC10", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Carbon fiber packing"],
            ['code' => "PAC11", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "PAN fiber packing reinforced with incorner & mesh"],
            ['code' => "PAC12", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Pure PTFE packing free oil"],
            ['code' => "PAC13", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Pure PTFE packing with silicone oil"],
            ['code' => "PAC14", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Carbonized fiber packing impregnated with PTFE"],
            ['code' => "PAC15", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Sinered PTFE packing"],
            ['code' => "PAC16", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Graphite PTFE packing"],
            ['code' => "PAC17", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Nomex fiber packing with silicon rubber core"],
            ['code' => "PAC18", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Nomex Fiber packing"],
            ['code' => "PAC19", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Graphite packing reinforced with Inconel wire & mesh wrapped"],
            ['code' => "PAC20", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "100% GFO packing"],
            ['code' => "PAC21", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Arcylic/Pan fiber packing with PTFE"],
            ['code' => "PAC22", 'prefix_code' => null, 'infix_code' => "O-PK", 'summary' => "Arcylic/Pan fiber packing with silicone rubber core"],
            ['code' => "PAL01", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 4488"],
            ['code' => "PAL02", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 4757"],
            ['code' => "PAL03", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 4758"],
            ['code' => "PAL04", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 4788"],
            ['code' => "PAL05", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 4789"],
            ['code' => "PAL06", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 5790"],
            ['code' => "PAL07", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYtex 4777"],
            ['code' => "PAL08", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYgraf 6118"],
            ['code' => "PAL09", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYgraf 6745 NG"],
            ['code' => "PAL10", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYgraf 6940"],
            ['code' => "PAL11", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYgraf 6940EF"],
            ['code' => "PAL12", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYgraf 6960"],
            ['code' => "PAL13", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYgraf 6988 EF"],
            ['code' => "PAL14", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYgraf 6995 NG"],
            ['code' => "PAL15", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYgraf T"],
            ['code' => "PAL16", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYgraf TSP"],
            ['code' => "PAL17", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "HEPHAISTOS 2000 G"],
            ['code' => "PAL18", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "HEPHAISTOS 2000 T"],
            ['code' => "PAL19", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 3206"],
            ['code' => "PAL20", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 3206AL"],
            ['code' => "PAL21", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 3206S"],
            ['code' => "PAL22", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 3206SO"],
            ['code' => "PAL23", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 3207"],
            ['code' => "PAL24", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 4308"],
            ['code' => "PAL25", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 7189"],
            ['code' => "PAL26", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 2775"],
            ['code' => "PAL27", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 2790"],
            ['code' => "PAL28", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 2790 AL"],
            ['code' => "PAL29", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 7188"],
            ['code' => "PAL30", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYtex 2761"],
            ['code' => "PAL31", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 1779"],
            ['code' => "PAL32", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYtex 14"],
            ['code' => "PAL33", 'prefix_code' => null, 'infix_code' => "L-PK", 'summary' => "LATTYflon 3210"],


            ['code' => "PLR PCBE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Black Sustarin (POM C) Rod"],
            ['code' => "PLR PCNE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Natural Sustarin (POM C) Rod"],
            ['code' => "PLR PGNE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Natural Sustamid 6G (PA6G) Rod"],
            ['code' => "PLR PGBE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Black Sustamid 6G (PA6G) Rod"],
            ['code' => "PLR P6NE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Natural Sustamid 6 (PA6) Rod"],
            ['code' => "PLR P6BE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Black Sustamid 6 (PA6) Rod"],
            ['code' => "PLR PKNE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Natural Sustapeek(PEEK) Rod"],
            ['code' => "PLR PKBE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Black Sustapeek(PEEK) Rod"],
            ['code' => "PLS PCNE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Natural Sustarin (POM C) Sheet"],
            ['code' => "PLS PCBE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Black Sustarin (POM C) Sheet"],
            ['code' => "PLS PGNE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Natural Sustamid 6G (PA6G) Sheet"],
            ['code' => "PLS PWNE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Natural Polystone M (UHMW-PE) Sheet"],
            ['code' => "PLS PWYE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Yellow Polystone M (UHMW-PE) Sheet"],
            ['code' => "PLS PWGE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Green Polystone M (UHMW-PE) Sheet"],
            ['code' => "PLS PKNE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Natural Sustapeek(PEEK) Sheet"],
            ['code' => "PLS PKBE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Black Sustapeek(PEEK) Sheet"],
            ['code' => "PLT PCNE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Natural Sustarin (POM C) Tube"],
            ['code' => "PLS PWYC", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "C-Yellow UHMW-PE Sheet"],
            ['code' => "PLS P6NC", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "C-Natural PA6 Sheet"],
            ['code' => "PLS PENC", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "White PE Sheet"],
            ['code' => "PLS NYBN", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Black Nytatron GSM Sheet"],
            ['code' => "PLS PCNN", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Natural PC Polycarbonate Sheet"],
            ['code' => "PLS P5NE", 'prefix_code' => null, 'infix_code' => "Pls", 'summary' => "Natural PE-500 sheet"],

            ['code' => "PR PUC", 'prefix_code' => null, 'infix_code' => "PTFE_R", 'summary' => "C-Pure PTFE Rod",],
            ['code' => "PR CAC", 'prefix_code' => null, 'infix_code' => "PTFE_R", 'summary' => "C-Carbon PTFE Rod",],
            ['code' => "PR GRC", 'prefix_code' => null, 'infix_code' => "PTFE_R", 'summary' => "C-Graphite PTFE Rod",],
            ['code' => "PR GLC", 'prefix_code' => null, 'infix_code' => "PTFE_R", 'summary' => "C-Glass PTFE Rod",],
            ['code' => "PR BRC", 'prefix_code' => null, 'infix_code' => "PTFE_R", 'summary' => "C-Bronze PTFE Rod",],
            ['code' => "PR PUE", 'prefix_code' => null, 'infix_code' => "PTFE_R", 'summary' => "E-Pure PTFE Rod",],
            ['code' => "PR CAE", 'prefix_code' => null, 'infix_code' => "PTFE_R", 'summary' => "E-Carbon PTFE Rod",],
            ['code' => "PR GRE", 'prefix_code' => null, 'infix_code' => "PTFE_R", 'summary' => "E-Graphite PTFE Rod",],
            ['code' => "PR GLE", 'prefix_code' => null, 'infix_code' => "PTFE_R", 'summary' => "E-Glass PTFE Rod",],
            ['code' => "PR BRE", 'prefix_code' => null, 'infix_code' => "PTFE_R", 'summary' => "E-Bronze PTFE Rod",],
            ['code' => "PT PUC", 'prefix_code' => null, 'infix_code' => "PTFE_T", 'summary' => "C-Pure PTFE Tube",],
            ['code' => "PT CAC", 'prefix_code' => null, 'infix_code' => "PTFE_T", 'summary' => "C-Carbon PTFE Tube",],
            ['code' => "PT GRC", 'prefix_code' => null, 'infix_code' => "PTFE_T", 'summary' => "C-Graphite PTFE Tube",],
            ['code' => "PT GLC", 'prefix_code' => null, 'infix_code' => "PTFE_T", 'summary' => "C-Glass PTFE Tube",],
            ['code' => "PT BRC", 'prefix_code' => null, 'infix_code' => "PTFE_T", 'summary' => "C-Bronze PTFE Tube",],
            ['code' => "PT PUE", 'prefix_code' => null, 'infix_code' => "PTFE_T", 'summary' => "E-Pure PTFE Tube",],
            ['code' => "PT CAE", 'prefix_code' => null, 'infix_code' => "PTFE_T", 'summary' => "E-Carbon PTFE Tube",],
            ['code' => "PT GRE", 'prefix_code' => null, 'infix_code' => "PTFE_T", 'summary' => "E-Graphite PTFE Tube",],
            ['code' => "PT GLE", 'prefix_code' => null, 'infix_code' => "PTFE_T", 'summary' => "E-Glass PTFE Tube",],
            ['code' => "PT BRE", 'prefix_code' => null, 'infix_code' => "PTFE_T", 'summary' => "E-Bronze PTFE Tube",],

            ['code' => "HPP", 'prefix_code' => null, 'infix_code' =>	"PTFE_H" , 'summary' => "Pure PTFE (Teflon) Hose"],	

            ['code' => "CPGL", 'prefix_code' => null, 'infix_code' => "Cer-PK", 'summary' => "Ceramic fiber packing with glass fiber reinforced "],
            ['code' => "CRSW", 'prefix_code' => null, 'infix_code' => "Cer-PK", 'summary' => "Ceramic fiber rope with steel wire reinforced"],
            ['code' => "CTGL", 'prefix_code' => null, 'infix_code' => "Cer-PK", 'summary' => "Ceramic fiber tape with glass fiber reinforced"],
            ['code' => "ETGL", 'prefix_code' => null, 'infix_code' => "Cer-PK", 'summary' => "E-glass fiber tape"],

            ['code' => "EP", 'prefix_code' => null, 'infix_code' => "Exp-PTFE", 'summary' => "Expanded PTFE Tape"], 	

            ['code' => "RCC01", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Solid Red Silicone Cord"],
            ['code' => "RCV01", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Solid Red Silicone Cord"],
            ['code' => "RCE01", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Solid Red Silicone Cord"],
            ['code' => "RCC02", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Solid transparent Silicone Cord"],
            ['code' => "RCV02", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Solid transparent Silicone Cord"],
            ['code' => "RCE02", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Solid transparent Silicone Cord"],
            ['code' => "RCC03", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Foam Red Silicone Cord"],
            ['code' => "RCV03", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Foam Red Silicone Cord"],
            ['code' => "RCE03", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Foam Red Silicone Cord"],
            ['code' => "RCC04", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Foam White Silicone Cord"],
            ['code' => "RCV04", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Foam White Silicone Cord"],
            ['code' => "RCE04", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Foam White Silicone Cord"],
            ['code' => "RCC05", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Black NBR Rubber Cord"],
            ['code' => "RCV05", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Black NBR Rubber Cord"],
            ['code' => "RCE05", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Black NBR Rubber Cord"],
            ['code' => "RCC06", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Black EPDM Rubber Cord"],
            ['code' => "RCV06", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Black EPDM Rubber Cord"],
            ['code' => "RCE06", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Black EPDM Rubber Cord"],
            ['code' => "RCC07", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Black FKM(Viton) Rubber Cord"],
            ['code' => "RCV07", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Black FKM(Viton) Rubber Cord"],
            ['code' => "RCE07", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Black FKM(Viton) Rubber Cord"],
            ['code' => "RSC01", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Solid Red Silicone Strip"],
            ['code' => "RSV01", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Solid Red Silicone Strip"],
            ['code' => "RSE01", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Solid Red Silicone Strip"],
            ['code' => "RSC02", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Solid transparent Silicone Strip"],
            ['code' => "RSV02", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Solid transparent Silicone Strip"],
            ['code' => "RSE02", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Solid transparent Silicone Strip"],
            ['code' => "RSC03", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Foam Red Silicone Strip"],
            ['code' => "RSV03", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Foam Red Silicone Strip"],
            ['code' => "RSE03", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Foam Red Silicone Strip"],
            ['code' => "RSC04", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Foam White Silicone Strip"],
            ['code' => "RSV04", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Foam White Silicone Strip"],
            ['code' => "RSE04", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Foam White Silicone Strip"],
            ['code' => "RSC05", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Black NBR Rubber Strip"],
            ['code' => "RSV05", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Black NBR Rubber Strip"],
            ['code' => "RSE05", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Black NBR Rubber Strip"],
            ['code' => "RSC06", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Black EPDM Rubber Strip"],
            ['code' => "RSV06", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Black EPDM Rubber Strip"],
            ['code' => "RSE06", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Black EPDM Rubber Strip"],
            ['code' => "RSC07", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "C- Black FKM(Viton) Rubber Strip"],
            ['code' => "RSV07", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "V- Black FKM(Viton) Rubber Strip"],
            ['code' => "RSE07", 'prefix_code' => null, 'infix_code' => "Rub strip", 'summary' => "E- Black FKM(Viton) Rubber Strip"],
            ['code' => "ROC01", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "C- Black NBR Rubber O-ring"],
            ['code' => "ROV01", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "V- Black NBR Rubber O-ring"],
            ['code' => "ROE01", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "E- Black NBR Rubber O-ring"],
            ['code' => "ROC02", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "C- Black EPDM Rubber O-ring"],
            ['code' => "ROV02", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "V- Black EPDM Rubber O-ring"],
            ['code' => "ROE02", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "E- Black EPDM Rubber O-ring"],
            ['code' => "ROC03", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "C- Black FKM(Viton) Rubber O-ring"],
            ['code' => "ROV03", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "V- Black FKM(Viton) Rubber O-ring"],
            ['code' => "ROE03", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "E- Black FKM(Viton) Rubber O-ring"],
            ['code' => "ROC04", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "C- Solid Red Silicone O-ring"],
            ['code' => "ROV04", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "V- Solid Red Silicone O-ring"],
            ['code' => "ROE04", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "E- Solid Red Silicone O-ring"],
            ['code' => "ROC05", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "C- Solid transparent Silicone O-ring"],
            ['code' => "ROV05", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "V- Solid transparent Silicone O-ring"],
            ['code' => "ROE05", 'prefix_code' => null, 'infix_code' => "O-ring", 'summary' => "E- Solid transparent Silicone O-ring"],

            ['code' => "GC08", 'prefix_code' => null, 'infix_code' => "Gra nen", 'summary' => "Graphite nén"],
            ['code' => "BST", 'prefix_code' => null, 'infix_code' => "KAM", 'summary' => "Basic type"],
            ['code' => "IOR", 'prefix_code' => null, 'infix_code' => "KAM", 'summary' => "Integral outer ring"],
            ['code' => "LOR", 'prefix_code' => null, 'infix_code' => "KAM", 'summary' => "Loose outer ring"],

            ['code' => "DJ", 'prefix_code' => null, 'infix_code' => "DBJ", 'summary' => "Double jacketed gasket"],	
        ]);
    }
}
