version: '3'
services:
  legia:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
      - "8080:8080"
      - "13714:13714"
    networks:
      - laravel
  mariadb:
    image: mariadb:latest
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "81:80"
    depends_on:
      - legia
    networks:
      - laravel
networks:
  laravel: